# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'ciskoh'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu: 
  - name: My work
    submenu:
      - name: My research
        link: /projects/my_research
      - name: My apps
        link: /projects/my_apps
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: About
    link: /about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: https://github.com/ciskoh
      - name: LinkedIn
        icon: linkedin-square
        link: https://www.linkedin.com/in/matteojriva
    
